### ISSUE TITLE
Before anyone else thinks up something really sarcastic, a few questions pop up in my head: Are you new to programming? Or new to Java? Or new to Github? New to the internet and posting to message boards?

### ISSUE THREAD

**Issue by Fremont2** [jbloch/effective-java-3e-source-code#6]
Before anyone else thinks up something really sarcastic, a few questions pop up in my head: Are you new to programming? Or new to Java? Or new to Github? New to the internet and posting to message boards? 
You asked a really open-ended question.

**Comment by sannidhi01** [comment]
What does this suppose to mean? What's the reference?

**Comment by Fremont2** [comment]
I copied it
